### ISSUE TITLE
文档更新了，那个adapters/config.py怎么没了，部署的时候报错

### ISSUE THREAD

**Issue by djdjfjfkeocj** [MaiM-with-u/MaiBot#751]
### 检查项

- [x] 我确认此问题在所有分支的最新版本中依旧存在
- [x] 我确认在 Issues 列表中并无其他人已经提出过与此问题相同或相似的问题
- [x] 我使用了 Docker

### 使用的分支

main

### 具体版本号

不知道啊，目前的最新版，docker直接拉的

### 遇到的问题

![Image](https://github.com/user-attachments/assets/42c37393-7acd-439f-907b-d3ef801e5de0)

### 报错信息

部署后报错没有adapters/config.py

### 系统环境

unraid

### Python 版本

docker拉取的

**Comment by infinitycat233** [comment]
去拉dev的docker-compose.yml，新版更新了adapter更改了docker-compose，main分支还没合并

**Comment by djdjfjfkeocj** [comment]
> 去拉dev的docker-compose.yml，新版更新了adapter更改了docker-compose，main分支还没合并

怎么拉？把main改成dev吗？
bug多吗？要不我先等合并？

**Comment by infinitycat233** [comment]
没啥影响只是更新的adapter

**Comment by kanocence** [comment]
> 没啥影响只是更新的adapter

注意到dev中的adapters和napcat端口配置有变化，请问该怎么配置

目前我的是这样，现在服务都启动了但是消息好像没通
```
adapters:
    ports:
        - '18002:18002'
napcat:
    ports:
        - '6099:6099'
        - '8095:8095'
 ```
