### ISSUE TITLE
docker 版本接收消息后无法处理

### ISSUE THREAD

**Issue by laomu61996** [MaiM-with-u/MaiBot#875]
### 检查项

- [x] 我确认此问题在所有分支的最新版本中依旧存在
- [x] 我确认在 Issues 列表中并无其他人已经提出过与此问题相同或相似的问题
- [x] 我使用了 Docker

### 使用的分支

main

### 具体版本号

0.6.2

### 遇到的问题

按照文档流程成功部署并运行后，napcat正常连接到adapters，发送消息core没有任何反应
日志如下

### 报错信息

maim-bot-napcat    | WebSocket反向服务: ws://adapters:8095, : 已启动
maim-bot-napcat    | 
maim-bot-napcat    | 04-28 11:41:03 [info] 小春 | 接收 <- 群聊 [好玩(103114282)] [春日野穹(1111111)] @小春 (2222222)  111
maim-bot-napcat    | 04-28 11:41:28 [info] 小春 | 接收 <- 群聊 [好玩(103114282)] [春日野穹(1111111)] @小春 (2222222)  111
maim-bot-mongo     | {"t":{"$date":"2025-04-28T11:52:59.058+08:00"},"s":"I",  "c":"WTCHKPT",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":{"ts_sec":1745812379,"ts_usec":58526,"thread":"1:0x79068d8236c0","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":7,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 72, snapshot max: 72 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 352"}}}
maim-bot-adapters  | 2025-04-28 11:53:00 | INFO     | src.message_queue:check_timeout_response:42 - 已删除 0 条超时响应消息
maim-bot-core      | 04-28 11:53 | 心情 | [情绪状态]愉悦度: 0.00, 唤醒度: 0.00, 心情: 平静
maim-bot-adapters  | 2025-04-28 11:53:10 | INFO     | src.message_queue:check_timeout_response:42 - 已删除 0 条超时响应消息
maim-bot-adapters  | 2025-04-28 11:53:20 | INFO     | src.message_queue:check_timeout_response:42 - 已删除 0 条超时响应消息
maim-bot-adapters  | 2025-04-28 11:53:30 | INFO     | src.message_queue:check_timeout_response:42 - 已删除 0 条超时响应消息
maim-bot-core      | 04-28 11:53 | 心情 | [情绪状态]愉悦度: 0.00, 唤醒度: 0.00, 心情: 平静
maim-bot-adapters  | 2025-04-28 11:53:40 | INFO     | src.message_queue:check_timeout_response:42 - 已删除 0 条超时响应消息
maim-bot-adapters  | 2025-04-28 11:53:50 | INFO     | src.message_queue:check_timeout_response:42 - 已删除 0 条超时响应消息
maim-bot-mongo     | {"t":{"$date":"2025-04-28T11:53:59.061+08:00"},"s":"I",  "c":"WTCHKPT",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":{"ts_sec":1745812439,"ts_usec":61958,"thread":"1:0x79068d8236c0","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":7,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 74, snapshot max: 74 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 352"}}}
maim-bot-adapters  | 2025-04-28 11:54:00 | INFO     | src.message_queue:check_timeout_response:42 - 已删除 0 条超时响应消息
maim-bot-core      | 04-28 11:54 | chat_stream | 聊天流自动保存完成
maim-bot-core      | 04-28 11:54 | 心情 | [情绪状态]愉悦度: 0.00, 唤醒度: 0.00, 心情: 平静
maim-bot-core      | 04-28 11:54 | llm_statistics | 
maim-bot-core      | 

### 系统环境

ubuntu 22.04

### Python 版本

官方docker内置

**Comment by YSB-AZhang** [comment]
我是按照“MaimCore版windows部署”文档一步步部署的，同样出现了该问题，没有任何报错提示，adapter窗口中显示“发送到Maibot处理消息”，但maibot窗口没有任何动静。
除了这个之外，在记忆遗忘、生成日程、保存/删除表情包上均表现正常。
但是如果在配置文档中打开了私聊选项，从小窗和麦麦聊天，她是能够回应的。
（我第一次发issue如果有格式错误还请见谅）

**Comment by Salinoia** [comment]
> 我是按照“MaimCore版windows部署”文档一步步部署的，同样出现了该问题，没有任何报错提示，adapter窗口中显示“发送到Maibot处理消息”，但maibot窗口没有任何动静。 除了这个之外，在记忆遗忘、生成日程、保存/删除表情包上均表现正常。 但是如果在配置文档中打开了私聊选项，从小窗和麦麦聊天，她是能够回应的。 （我第一次发issue如果有格式错误还请见谅）

遇到了相同的问题，所有消息配置均正常出现，但是包括私聊麦麦依然都没有回复；
观察日志来说：
不同组件之间协作似乎正常，但core除了自身活动和持续性的“ 心情 | [情绪状态]愉悦度: 0.00, 唤醒度: 0.00, 心情: 平静”以外并无别的消息发送；
napcat能够正常接收私聊和群聊消息，但不存在反馈信息，怀疑是此处存在问题

**Comment by Salinoia** [comment]
> 遇到了相同的问题，所有消息配置均正常出现，但是包括私聊麦麦依然都没有回复； 观察日志来说，不同组件之间协作似乎正常：
> 
> * mongodb是在持续性发出“DEBUG_1”级别的信息，应该不存在问题；
> * core除了自身活动和持续性的“ 心情 | [情绪状态]愉悦度: 0.00, 唤醒度: 0.00, 心情: 平静”以外并无别的消息发送；
> * napcat能够正常接收私聊和群聊消息，但不存在反馈信息，怀疑是此处与core的通信存在问题(?)，不过这里应该是通了的啊，难道是反向代理吗🤔

找到问题了，新版的Adaptor支持存在一定问题，需要回退到4.24版本才可以解决
https://github.com/MaiM-with-u/MaiBot-Napcat-Adapter/tree/dc25e51ec956ae9467e81d05edce5eb8d3edd9b6

**Comment by Salinoia** [comment]
修改源文件 ./maibot/docker-config.yaml，更换adaptor版本源即可：
``` yaml
{
  "type": "git_commit_log",
  "commit_hash": "a1b2c3d4e5",
  "author": "Your Name <your.email@example.com>",
  "date": "2025-04-24 04:49:06 +0000",
  "message": "Update Docker image tag to main-20250424044906",
  "changes": [
    {
      "file": "docker-compose.yml",
      "diff": [
        "-    image: unclas/maimbot-adapter:latest",
        "+    image: unclas/maimbot-adapter:main-20250424044906"
      ],
      "description": "Changed from 'latest' tag to specific build tag 'main-20250424044906'"
    }
  ],
  "metadata": {
    "build_reason": "Deploying specific tested version",
    "build_timestamp": "2025-04-24T04:49:06Z",
    "versioning_scheme": "main-YYYYMMDDHHMMSS"
  }
}
```
